name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Run tests
        run: |
          mkdir -p .pytest_basetemp
          uv run --extra test pytest --basetemp .pytest_basetemp/ci -q
